# Generated by Django 4.1.3 on 2022-12-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tital', models.CharField(max_length=255)),
                ('discription', models.TextField()),
                ('upload_by', models.CharField(max_length=255)),
            ],
        ),
    ]
