# Generated by Django 4.1.3 on 2023-01-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='upload_by',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
