# Generated by Django 4.1.3 on 2023-01-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_feedback_upload_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='tital',
            new_name='title',
        ),
    ]
