# Generated by Django 4.1.3 on 2023-01-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_rename_discription_blog_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=2),
            preserve_default=False,
        ),
    ]
