# Generated by Django 4.1.3 on 2023-01-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_blog_upload_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='upload_time',
        ),
    ]
